### ISSUE TITLE
error attempt to call a nil value (field 'showNotification')

### ISSUE THREAD

**Issue by MIGUELZXC** [visibait/vb-banking#1]
![image](https://user-images.githubusercontent.com/67492122/120563718-a9deb400-c3df-11eb-94f0-d8c0e91ad7d1.png)

**Comment by MIGUELZXC** [comment]
tengo es_extended 1.1

**Comment by Ghavio1516** [comment]
change the esx.shownotification to this
TriggerClientEvent('esx:showNotification', _source, _U('insert translation here'))

or if you have mythic notify,use this

	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = 'insert text here.', length = 4500, style = { ['background-color'] = '#ffffff', ['color'] = '#000000' } })
