### ISSUE TITLE
Problema al salir de la pantalla del banco

### ISSUE THREAD

**Issue by m4ng3l** [visibait/vb-banking#2]
Cuando estás dentro de la interfaz interactuando con el banco todo bien, el problema viene cuando sales de este ya sea cerrando sesión o dándole al ESC.

¿Alguna idea de como solucionarlo?

**Comment by visibait** [comment]
Si le cambiaste el nombre al script, ahí tienes el fallo.

**Comment by m4ng3l** [comment]
Si era eso, le quite el vb y el guión, ahora va de lujo. Muchisimas gracias
